{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels" . | indent 4 }}
data:
  #clientPassword: {{ randAscii 20 | b64enc }}
  #clusterPassword: {{ randAscii 20 | b64enc }}
  clientPassword: {{ "artemis" | b64enc }}
  clusterPassword: {{ "artemis" | b64enc }}

{{- end }}
